// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBilheteira.Data;

namespace WebBilheteira.Migrations
{
    [DbContext(typeof(WebBilheteiraContext))]
    partial class WebBilheteiraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bilheteira.Bilhete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataEspetaculo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EspetaculoId")
                        .HasColumnType("int");

                    b.Property<int>("NumBilhetes")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspetaculoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Bilhete");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataEspetaculo = new DateTime(2022, 11, 19, 14, 54, 44, 124, DateTimeKind.Local).AddTicks(5234),
                            EspetaculoId = 1,
                            NumBilhetes = 20,
                            Preco = 50,
                            SalaId = 2
                        },
                        new
                        {
                            Id = 2,
                            DataEspetaculo = new DateTime(2022, 11, 19, 14, 54, 44, 132, DateTimeKind.Local).AddTicks(8055),
                            EspetaculoId = 2,
                            NumBilhetes = 30,
                            Preco = 40,
                            SalaId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataEspetaculo = new DateTime(2022, 11, 19, 14, 54, 44, 132, DateTimeKind.Local).AddTicks(8078),
                            EspetaculoId = 3,
                            NumBilhetes = 60,
                            Preco = 30,
                            SalaId = 4
                        },
                        new
                        {
                            Id = 4,
                            DataEspetaculo = new DateTime(2022, 11, 19, 14, 54, 44, 132, DateTimeKind.Local).AddTicks(8082),
                            EspetaculoId = 3,
                            NumBilhetes = 70,
                            Preco = 70,
                            SalaId = 3
                        });
                });

            modelBuilder.Entity("Bilheteira.Espetaculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Elenco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoEspetaculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoEspetaculoId");

                    b.ToTable("Espetaculo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lago dos cisnes",
                            TipoEspetaculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantas da opera",
                            TipoEspetaculoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fanoches",
                            TipoEspetaculoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Princepesinho",
                            TipoEspetaculoId = 2
                        });
                });

            modelBuilder.Entity("Bilheteira.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumLugares")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sala");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endereco = "Porto",
                            Nome = "Cineteatro",
                            NumLugares = 50
                        },
                        new
                        {
                            Id = 2,
                            Endereco = "Porto",
                            Nome = "Batalha",
                            NumLugares = 40
                        },
                        new
                        {
                            Id = 3,
                            Endereco = "Braga",
                            Nome = "Circo",
                            NumLugares = 50
                        },
                        new
                        {
                            Id = 4,
                            Endereco = "Guimaraes",
                            Nome = "Mamede",
                            NumLugares = 30
                        });
                });

            modelBuilder.Entity("Bilheteira.TipoEspetaculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEspetaculo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Musical"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Teatro"
                        });
                });

            modelBuilder.Entity("Bilheteira.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizador");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ze Pintas",
                            UserName = "zepin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maria Calas Pintas",
                            UserName = "macalas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jose oliveira",
                            UserName = "zeo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "jonana souzas",
                            UserName = "jasou"
                        });
                });

            modelBuilder.Entity("Bilheteira.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BilheteId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizadorID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilheteId");

                    b.HasIndex("UtilizadorID");

                    b.ToTable("Venda");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilheteId = 1,
                            UtilizadorID = 1
                        },
                        new
                        {
                            Id = 2,
                            BilheteId = 1,
                            UtilizadorID = 2
                        },
                        new
                        {
                            Id = 3,
                            BilheteId = 2,
                            UtilizadorID = 3
                        },
                        new
                        {
                            Id = 4,
                            BilheteId = 3,
                            UtilizadorID = 4
                        });
                });

            modelBuilder.Entity("Bilheteira.Bilhete", b =>
                {
                    b.HasOne("Bilheteira.Espetaculo", "Espetaculo")
                        .WithMany("Bilhetes")
                        .HasForeignKey("EspetaculoId");

                    b.HasOne("Bilheteira.Sala", "Sala")
                        .WithMany("Bilhetes")
                        .HasForeignKey("SalaId");

                    b.Navigation("Espetaculo");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Bilheteira.Espetaculo", b =>
                {
                    b.HasOne("Bilheteira.TipoEspetaculo", "TipoEspetaculo")
                        .WithMany("Espetaculos")
                        .HasForeignKey("TipoEspetaculoId");

                    b.Navigation("TipoEspetaculo");
                });

            modelBuilder.Entity("Bilheteira.Venda", b =>
                {
                    b.HasOne("Bilheteira.Bilhete", "Bilhete")
                        .WithMany("Vendas")
                        .HasForeignKey("BilheteId");

                    b.HasOne("Bilheteira.Utilizador", "Utilizador")
                        .WithMany("Vendas")
                        .HasForeignKey("UtilizadorID");

                    b.Navigation("Bilhete");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Bilheteira.Bilhete", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Bilheteira.Espetaculo", b =>
                {
                    b.Navigation("Bilhetes");
                });

            modelBuilder.Entity("Bilheteira.Sala", b =>
                {
                    b.Navigation("Bilhetes");
                });

            modelBuilder.Entity("Bilheteira.TipoEspetaculo", b =>
                {
                    b.Navigation("Espetaculos");
                });

            modelBuilder.Entity("Bilheteira.Utilizador", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
